apiVersion: v2
name: aks-app
version: 0.1.0
dependencies:
  - name: frontend
    version: 0.1.0
    repository: "file://charts/frontend"
  - name: backend
    version: 0.1.0
    repository: "file://charts/backend"
  - name: ingress
    version: 0.1.0
    repository: "file://charts/ingress"
