apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: azure-kv
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"
    keyvaultName: {{ .Values.keyVault.name }}
    cloudName: ""
    objects: |
      array:
        - |
          objectName: STRIPE_SECRET_KEY
          objectType: secret
        - |
          objectName: STRIPE_WEBHOOK_SECRET
          objectType: secret
        - |
          objectName: PAYPAL_CLIENT_ID
          objectType: secret
        - |
          objectName: PAYPAL_CLIENT_SECRET
          objectType: secret
    tenantId: {{ .Values.keyVault.tenantId }}
